### PR TITLE
Make error handling more robust

### LINKED ISSUE #9: SAXParseException doesn't seem to be captured correctly and cause the receive-loop to end prematurely
```
29 Oct 2018 21:00:36.662<14>1 2018-10-29T12:00:36Z 5f0b4345e6e0 big-enos.worker.1 103200 - ] [async-dispatch-1] WARN sqs-utils.core - Queue https://sqs.us-west-2.amazonaws.com/<REDACTED>/action_service_incoming_prod received a nil body message: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
29 Oct 2018 21:00:36.664<14>1 2018-10-29T12:00:36Z 5f0b4345e6e0 big-enos.worker.1 103200 - ] [async-dispatch-1] INFO sqs-utils.core - Terminating receive-loop for https://sqs.us-west-2.amazonaws.com/<REDACTED>/action_service_incoming_prod
29 Oct 2018 21:00:36.665<14>1 2018-10-29T12:00:36Z 5f0b4345e6e0 big-enos.worker.1 103200 - ] [async-dispatch-1] WARN sqs-utils.core - Receive-loop terminated for {:count 2, :started-at #clj-time/date-time "2018-10-26T01:34:15.947Z", :restart-count 0, :restarted-at nil, :queue-url "https://sqs.us-west-2.amazonaws.com/<REDACTED>/action_service_incoming_prod", :this-pass-started-at #clj-time/date-time "2018-10-29T12:00:36.595Z", :loop-duration 296780}
29 Oct 2018 21:00:37.483<14>1 2018-10-29T12:00:37Z 5f0b4345e6e0 big-enos.worker.1 103200 - ] [async-dispatch-4] WARN sqs-utils.core - Queue https://sqs.us-west-2.amazonaws.com/<REDACTED>/campaign_heartbeat_prod.fifo received a nil body message: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
29 Oct 2018 21:01:37.514<14>1 2018-10-29T12:01:37Z 5f0b4345e6e0 big-enos.worker.1 103200 - ] [async-dispatch-4] INFO sqs-utils.core - Terminating receive-loop for https://sqs.us-west-2.amazonaws.com/<REDACTED>/campaign_heartbeat_prod.fifo
29 Oct 2018 21:01:37.515<14>1 2018-10-29T12:01:37Z 5f0b4345e6e0 big-enos.worker.1 103200 - ] [async-dispatch-4] WARN sqs-utils.core - Receive-loop terminated for {:count 630, :started-at #clj-time/date-time "2018-10-26T01:34:15.943Z", :restart-count 0, :restarted-at nil, :queue-url "https://sqs.us-west-2.amazonaws.com/<REDACTED>/campaign_heartbeat_prod.fifo", :this-pass-started-at #clj-time/date-time "2018-10-29T12:01:37.446Z", :loop-duration 296841}
```

It appears that this `org.xml.sax.SAXParseException` should have been handled in the `cond` https://github.com/Motiva-AI/sqs-utils/blob/6092ab1b43f8605c53c4113ad04709801ca7c2e4/src/sqs_utils/core.clj#L121 But instead it proceeded to the `:else` condition. And then on the next loop, `message` is evaluated as nil and the loop closes.

### PR DESCRIPTION
**Pull request by j0ni**
Fink-nottle passes processing errors through to client code as `Throwable` objects. I had assumed they were always created with `ex-info` inside fink-nottle error handling, and used the `clojure.lang.IExceptionInfo` interface.

This makes error handling more generic by catching all `Throwable` objects and restarting the handler loop, so some exceptions don't fall through to the client handler code.

I'm taking this opportunity to update our build to use the `circleci.test` runner we've used elsewhere, which allows for some removal of cruft.

Fixes #9

### CODE REVIEW

File: test/sqs_utils/core_test.clj [hunk 1]
```diff
@@ -36,12 +38,14 @@
...
-    (is (= {:testing 1}
-           (:message (<!! c))))))
+    (let [kill-fn (su/receive-loop! creds @test-queue-url c)]
+      (is (fn? kill-fn))
+      (is (= {:testing 2}
+             (:message (<!! c))))
+      (is (su/send-message creds @test-queue-url {:testing 1}))
+      (is (= {:testing 1}
+             (:message (<!! c))))
+      (kill-fn))))
```
Comment (j0ni) [inline test/sqs_utils/core_test.clj]: This drove me crazy, causing the tests to blow up locally - the loop was still going when it gets to `fink-nottle-error-handling-works`. So when we rebind `receive`, and send it messages via the stubbed replacement function, it would get picked up by the wrong loop (first call), leaving the other one hanging, blocked (second call). The `wait-for` predicate would eventually time out because there were 2 calls, not 1, and the test would fail.

It was confusing because I could see the trace being recorded by a handler in the log, with all the correct bits in it. But then I saw 2 different loops being restarted, for 2 different *queues*.

Oh well.
